[package]
name = "stackdump-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stackdump-core = { path = "../core", default-features = false }
arrayvec = { version = "0.7.2", default-features = false }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
gimli = { version = "0.26.1", optional = true }
arbitrary = { version = "1.0.3", optional = true, features = ["derive"] }

[features]
cortex-m = []
cortex-m-fpu = ["cortex-m"]
capture = []
std = ["gimli", "stackdump-core/std"]
fuzzing = ["arbitrary"]
default = ["capture"]
