[package]
name = "stackdump-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.17.0"
gimli = "0.26.1"
bitvec = "1.0.0"
stackdump-core = { path = "../core" }
thiserror = "1.0.30"
log = "0.4.14"

[dev-dependencies]
simple_logger = "2.1.0"
