[package]
name = "stackdump-trace"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tweedegolf/stackdump"
repository = "https://github.com/tweedegolf/stackdump"
readme = "README.md"
keywords = [ "stackdump"]
categories = ["embedded"]
description = "Crate for tracing stack dumps"

[dependencies]
addr2line = "0.17.0"
gimli = "0.26.1"
bitvec = "1.0.0"
stackdump-core = { version = "0.1.2", path = "../core" }
thiserror = "1.0.30"
log = "0.4.14"

[dev-dependencies]
simple_logger = "2.1.0"
