[package]
name = "stackdump-trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.17.0"
gimli = "0.26.1"
bitvec = "0.22.3"
stackdump-core = { path = "../core", default-features = false }
stackdump-capture = { path = "../capture", default-features = false, features = ["std", "cortex-m"] }
