[package]
name = "stackdump-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive", "color", "suggestions"] }
stackdump-trace = { path = "../trace" }
simple_logger = "2.1.0"
