[package]
name = "stackdump-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.2", default-features = false, features = ["serde"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
gimli = { version = "0.26.1", optional = true }
arbitrary = { version = "1", optional = true, features = ["derive"] }

[features]
std = ["arrayvec/std", "gimli", "serde/std"]
default = ["std"]
fuzzer = ["arbitrary"]