[package]
name = "stackdump-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }

[features]
std = ["arrayvec/std"]
default = ["std"]
